#!/bin/sh
### BEGIN INIT INFO
# Provides:          lddmodules
# Required-Start:    $local_fs $remote_fs $syslog $time
# Required-Stop:     $local_fs $remote_fs $syslog $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

EXTRA_DIR="/lib/modules/$(uname -r)/extra"

load_mod()  { modprobe "$1" 2>/dev/null || insmod "$EXTRA_DIR/$1.ko" 2>/dev/null || true; }
unload_mod(){ rmmod "$1" 2>/dev/null || true; }

do_start() {
  echo "[S98lddmodules] start: loading scull, faulty, hello"
  load_mod scull
  load_mod faulty
  load_mod hello
}
do_stop() {
  echo "[S98lddmodules] stop: unloading hello, faulty, scull"
  unload_mod hello
  unload_mod faulty
  unload_mod scull
}
case "$1" in start) do_start ;; stop) do_stop ;; restart) do_stop; do_start ;; *) echo "Usage: $0 {start|stop|restart}"; exit 1 ;; esac
exit 0

